In [76]:
#2022년 행정구역별 고등학생의 4년제 대학진학률
import pandas as pd

df = pd.read_csv('행정구역별_2022.csv',encoding='cp949' )
df1 = df.query('학제 in ["고등학교", "(일반고)", "(특목고)", "(특성화고)", "(자율고)"]')

df2= df1.rename(columns = {df1.columns[5]:"졸업후진학자",
                               df1.columns[6]:"졸업후취업자",
                               df1.columns[7]:"졸업후입대자",
                               df1.columns[8]:"졸업후기타",
                               df1.columns[9]:"국내전문대학진학자",
                               df1.columns[10]:"국내대학진학자",
                               df1.columns[11]:"국외전문대학진학자",
                               df1.columns[12]:"국외대학진학자"})



#고등학교=일반고+특목고+특성화고+자율고

df2_univ = df2.query('학제 in ["고등학교"]')
df2_univ['졸업자'] = df2_univ['졸업자'].astype('float')
df2_univ['국내대학진학자'] = df2_univ['국내대학진학자'].astype('float')

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2557845572.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_univ['졸업자'] = df2_univ['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2557845572.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_univ['국내대학진학자'] = df2_univ['국내대학진학자'].astype('float')

In [104]:
df2_univ['국내4년제대학진학률'] = (df2_univ['국내대학진학자']/df2_univ['졸업자'])
df2_univ

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3901176700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_univ['국내4년제대학진학률'] = (df2_univ['국내대학진학자']/df2_univ['졸업자'])

,시도,행정구역,학제,입학자,졸업자,졸업후진학자,졸업후취업자,졸업후입대자,졸업후기타,국내전문대학진학자,국내대학진학자,국외전문대학진학자,국외대학진학자,진학률,국내4년제대학진학률
4,서울,종로구,고등학교,2505,2742.0,1638,162,7,935,330,1285.0,0,23,0.468636,0.468636
15,서울,중구,고등학교,1770,2230.0,1043,396,95,696,364,671.0,0,8,0.300897,0.300897
25,서울,용산구,고등학교,1478,1794.0,1030,193,12,559,286,742.0,0,2,0.413601,0.413601
32,서울,성동구,고등학교,1251,1404.0,828,124,1,451,313,513.0,1,1,0.365385,0.365385
40,서울,광진구,고등학교,2485,2540.0,1628,22,3,887,337,1280.0,0,11,0.503937,0.503937
49,서울,동대문구,고등학교,2055,2270.0,1519,158,1,592,417,1100.0,1,1,0.484581,0.484581
57,서울,중랑구,고등학교,1982,2075.0,1458,132,3,482,543,915.0,0,0,0.440964,0.440964
64,서울,성북구,고등학교,2535,2852.0,1753,327,6,766,535,1213.0,0,5,0.425316,0.425316
73,서울,강북구,고등학교,1698,1846.0,1168,61,0,617,407,758.0,0,3,0.410618,0.410618
82,서울,도봉구,고등학교,1980,2167.0,1396,154,0,617,454,932.0,0,10,0.430088,0.430088
92,서울,노원구,고등학교,5616,6671.0,4243,516,126,1786,1381,2859.0,0,3,0.428571,0.428571
102,서울,은평구,고등학교,3946,4271.0,2718,444,22,1087,956,1754.0,0,8,0.410677,0.410677
112,서울,서대문구,고등학교,1623,1715.0,1218,75,5,417,241,975.0,0,2,0.568513,0.568513
121,서울,마포구,고등학교,1944,2050.0,1157,166,3,724,413,739.0,0,5,0.360488,0.360488
130,서울,양천구,고등학교,3938,4126.0,2440,63,2,1621,631,1805.0,0,4,0.437470,0.437470
138,서울,강서구,고등학교,4376,4940.0,3079,410,8,1443,949,2126.0,1,3,0.430364,0.430364
147,서울,구로구,고등학교,2987,3102.0,2207,184,2,709,926,1280.0,0,1,0.412637,0.412637
157,서울,금천구,고등학교,1264,1326.0,912,159,1,254,280,632.0,0,0,0.476621,0.476621
166,서울,영등포구,고등학교,1844,1989.0,1302,68,0,619,447,855.0,0,0,0.429864,0.429864
175,서울,동작구,고등학교,1783,1978.0,1188,217,2,571,451,734.0,0,3,0.371082,0.371082
183,서울,관악구,고등학교,2864,3059.0,1886,409,1,763,597,1283.0,0,6,0.419418,0.419418
193,서울,서초구,고등학교,3182,3196.0,1649,15,1,1531,261,1385.0,0,3,0.433354,0.433354
203,서울,강남구,고등학교,5847,5927.0,3119,321,44,2443,439,2661.0,0,19,0.448962,0.448962
214,서울,송파구,고등학교,4545,4900.0,2939,268,40,1653,717,2214.0,0,8,0.451837,0.451837
224,서울,강동구,고등학교,3609,3646.0,2362,180,3,1101,699,1652.0,0,11,0.453099,0.453099

In [85]:
df2_univ1 = df2_univ[['행정구역', '국내4년제대학진학률']]
df2_univ1.sort_values('국내4년제대학진학률', ascending = False)

     행정구역  국내4년제대학진학률
112  서대문구    0.568513
40    광진구    0.503937
49   동대문구    0.484581
157   금천구    0.476621
4     종로구    0.468636
224   강동구    0.453099
214   송파구    0.451837
203   강남구    0.448962
57    중랑구    0.440964
130   양천구    0.437470
193   서초구    0.433354
138   강서구    0.430364
82    도봉구    0.430088
166  영등포구    0.429864
92    노원구    0.428571
64    성북구    0.425316
183   관악구    0.419418
25    용산구    0.413601
147   구로구    0.412637
102   은평구    0.410677
73    강북구    0.410618
175   동작구    0.371082
32    성동구    0.365385
121   마포구    0.360488
15     중구    0.300897

In [108]:
#2022-일반고 대학진학률
df_univ_no = df2.query('학제 in ["(일반고)"]')
df_univ_no['졸업자'] = df_univ_no['졸업자'].astype('float')
df_univ_no['국내대학진학자'] = df_univ_no['국내대학진학자'].astype('float')
df_univ_no['일반고학생_국내4년제대학진학률'] = (df_univ_no['국내대학진학자']/df_univ_no['졸업자'])
df_univ_no1 = df_univ_no[['행정구역', '일반고학생_국내4년제대학진학률']]
df_univ_no1.sort_values('일반고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4040976775.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no['졸업자'] = df_univ_no['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4040976775.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no['국내대학진학자'] = df_univ_no['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4040976775.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no['일반고학생_국내4년제대학진학률'] = (df_univ_no['국내대학진학자']/df_univ_no['졸업자'])

     행정구역  일반고학생_국내4년제대학진학률
50    광진구          0.543192
16    강동구          0.541509
113   마포구          0.535772
93   동대문구          0.532656
158   송파구          0.520045
184   용산구          0.515415
26    강북구          0.498333
58    구로구          0.491269
103   동작구          0.486163
65    금천구          0.482645
5     강남구          0.481716
225   중랑구          0.478452
139   성동구          0.477082
215    중구          0.467186
148   성북구          0.461807
204   종로구          0.460458
41    관악구          0.460417
176  영등포구          0.458056
131   서초구          0.456702
167   양천구          0.448185
122  서대문구          0.438284
83    도봉구          0.437450
194   은평구          0.429735
74    노원구          0.422642
33    강서구          0.402329

In [109]:
#2022-특목고 대학진학률
df_univ_sp = df2.query('학제 in ["(특목고)"]')
df_univ_sp['졸업자'] = df_univ_sp['졸업자'].astype('float')
df_univ_sp['국내대학진학자'] = df_univ_sp['국내대학진학자'].astype('float')
df_univ_sp['특목고학생_국내4년제대학진학률'] = (df_univ_sp['국내대학진학자']/df_univ_sp['졸업자'])
df_univ_sp1 = df_univ_sp[['행정구역', '특목고학생_국내4년제대학진학률']]
df_univ_sp1.sort_values('특목고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4264912533.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp['졸업자'] = df_univ_sp['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4264912533.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp['국내대학진학자'] = df_univ_sp['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4264912533.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp['특목고학생_국내4년제대학진학률'] = (df_univ_sp['국내대학진학자']/df_univ_sp['졸업자'])

     행정구역  특목고학생_국내4년제대학진학률
159   금천구          0.821429
114  서대문구          0.768657
216   송파구          0.748148
226   강동구          0.669811
42    광진구          0.638710
149   구로구          0.636364
140   강서구          0.612676
17     중구          0.607692
6     종로구          0.599034
84    도봉구          0.569378
66    성북구          0.386486
205   강남구          0.263804
185   관악구          0.038095

In [110]:
#2022-특성화고 대학진학률
df_univ_sd = df2.query('학제 in ["(특성화고)"]')
df_univ_sd['졸업자'] = df_univ_sd['졸업자'].astype('float')
df_univ_sd['국내대학진학자'] = df_univ_sd['국내대학진학자'].astype('float')
df_univ_sd['특성화고학생_국내4년제대학진학률'] = (df_univ_sd['국내대학진학자']/df_univ_sd['졸업자'])
df_univ_sd1 = df_univ_sd[['행정구역', '특성화고학생_국내4년제대학진학률']]
df_univ_sd1.sort_values('특성화고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3791034630.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd['졸업자'] = df_univ_sd['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3791034630.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd['국내대학진학자'] = df_univ_sd['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3791034630.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd['특성화고학생_국내4년제대학진학률'] = (df_univ_sd['국내대학진학자']/df_univ_sd['졸업자'])

     행정구역  특성화고학생_국내4년제대학진학률
206   강남구           0.276515
132   양천구           0.265854
27    용산구           0.242424
7     종로구           0.232099
59    중랑구           0.198880
104   은평구           0.183086
227   강동구           0.170172
94    노원구           0.156926
34    성동구           0.149847
75    강북구           0.146067
186   관악구           0.141321
123   마포구           0.140187
150   구로구           0.138728
51   동대문구           0.133508
141   강서구           0.128174
168  영등포구           0.120603
67    성북구           0.117143
85    도봉구           0.114754
18     중구           0.109152
160   금천구           0.103846
177   동작구           0.096639
195   서초구           0.088235
217   송파구           0.082005

In [111]:
#2022-자율고 대학진학률
df_univ_ah = df2.query('학제 in ["(자율고)"]')
df_univ_ah['졸업자'] = df_univ_ah['졸업자'].astype('float')
df_univ_ah['국내대학진학자'] = df_univ_ah['국내대학진학자'].astype('float')
df_univ_ah['자율고학생_국내4년제대학진학률'] = (df_univ_ah['국내대학진학자']/df_univ_ah['졸업자'])
df_univ_ah1 = df_univ_ah[['행정구역', '자율고학생_국내4년제대학진학률']]
df_univ_ah1.sort_values('자율고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2475129840.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah['졸업자'] = df_univ_ah['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2475129840.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah['국내대학진학자'] = df_univ_ah['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2475129840.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah['자율고학생_국내4년제대학진학률'] = (df_univ_ah['국내대학진학자']/df_univ_ah['졸업자'])

     행정구역  자율고학생_국내4년제대학진학률
86    도봉구          0.648725
218   송파구          0.627507
105   은평구          0.614213
115  서대문구          0.606838
52   동대문구          0.588123
169  영등포구          0.552727
228   강동구          0.548148
207   강남구          0.529148
35    성동구          0.503289
76    강북구          0.501458
196   서초구          0.481426
19     중구          0.461741
8     종로구          0.455782
133   양천구          0.453488

In [2]:
#2021년 행정구역별 고등학생의 4년제 대학진학률
import pandas as pd

df11 = pd.read_csv('행정구역별2021.csv')
df12 = df11.query('학제 in ["고등학교", "(일반고)", "(특목고)", "(특성화고)", "(자율고)"]')

df13= df12.rename(columns = {df12.columns[5]:"졸업후진학자",
                             df12.columns[6]:"졸업후취업자",
                             df12.columns[7]:"졸업후입대자",
                             df12.columns[8]:"졸업후기타",
                             df12.columns[9]:"국내전문대학진학자",
                             df12.columns[10]:"국내대학진학자",
                             df12.columns[11]:"국외전문대학진학자",
                             df12.columns[12]:"국외대학진학자"})



#고등학교=일반고+특목고+특성화고+자율고

df13_univ = df13.query('학제 in ["고등학교"]')
df13_univ['졸업자'] = df13_univ['졸업자'].astype('float')
df13_univ['국내대학진학자'] = df13_univ['국내대학진학자'].astype('float')

df13_univ['국내4년제대학진학률'] = (df13_univ['국내대학진학자']/df13_univ['졸업자'])

df13_univ

C:\Users\onlyo\AppData\Local\Temp\ipykernel_24256\3177164605.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13_univ['졸업자'] = df13_univ['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_24256\3177164605.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13_univ['국내대학진학자'] = df13_univ['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_24256\3177164605.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13_univ['국내4년제대학진학률'] = (df13_univ['국내대학진학자']/df13_univ['졸업자'])

,시도,행정구역,학제,입학자,졸업자,졸업후진학자,졸업후취업자,졸업후입대자,졸업후기타,국내전문대학진학자,국내대학진학자,국외전문대학진학자,국외대학진학자,국내4년제대학진학률
4,서울,종로구,고등학교,2530,2813.0,1763,133,3,914,363,1390.0,0,10,0.494134
15,서울,중구,고등학교,1851,2274.0,1118,422,79,655,400,715.0,0,3,0.314424
25,서울,용산구,고등학교,1529,1827.0,1045,192,16,574,319,726.0,0,0,0.397373
32,서울,성동구,고등학교,1205,1709.0,1069,110,1,529,419,649.0,0,1,0.379754
40,서울,광진구,고등학교,2304,2371.0,1601,33,4,733,396,1184.0,0,21,0.499367
49,서울,동대문구,고등학교,2089,2285.0,1438,140,4,703,404,1032.0,0,2,0.451641
57,서울,중랑구,고등학교,1805,2059.0,1386,159,12,502,535,851.0,0,0,0.413307
64,서울,성북구,고등학교,2480,2667.0,1684,298,2,683,511,1164.0,0,9,0.436445
73,서울,강북구,고등학교,1640,1711.0,1100,56,0,555,394,697.0,0,9,0.407364
82,서울,도봉구,고등학교,1973,2109.0,1410,104,0,595,446,952.0,0,12,0.451399
92,서울,노원구,고등학교,5836,6561.0,4058,505,97,1901,1383,2661.0,1,13,0.405578
102,서울,은평구,고등학교,3804,4079.0,2515,515,11,1038,846,1660.0,1,8,0.406962
112,서울,서대문구,고등학교,1503,1730.0,1176,100,13,441,253,921.0,0,2,0.532370
121,서울,마포구,고등학교,1811,1848.0,1136,122,0,590,393,740.0,0,3,0.400433
131,서울,양천구,고등학교,3905,4085.0,2502,67,0,1516,728,1770.0,2,2,0.433293
139,서울,강서구,고등학교,4298,5021.0,3128,381,5,1507,1073,2043.0,1,11,0.406891
148,서울,구로구,고등학교,2900,3008.0,1978,159,1,870,811,1167.0,0,0,0.387965
158,서울,금천구,고등학교,1220,1389.0,916,166,0,307,282,633.0,0,1,0.455724
167,서울,영등포구,고등학교,1742,1896.0,1207,66,0,623,420,785.0,0,2,0.414030
176,서울,동작구,고등학교,1798,1934.0,1124,222,6,582,377,745.0,0,2,0.385212
184,서울,관악구,고등학교,2802,3065.0,1769,394,3,899,549,1215.0,0,5,0.396411
194,서울,서초구,고등학교,3063,3217.0,1755,29,3,1430,279,1456.0,0,20,0.452596
204,서울,강남구,고등학교,5696,5805.0,3121,294,37,2353,486,2618.0,0,17,0.450991
215,서울,송파구,고등학교,4447,4730.0,3036,247,61,1386,927,2098.0,0,11,0.443552
225,서울,강동구,고등학교,3428,3572.0,2297,176,4,1095,635,1651.0,0,11,0.462206

In [4]:
df13_univ1 = df13_univ[['행정구역', '국내전문대학진학자']]
df13_univ1

     행정구역 국내전문대학진학자
4     종로구       363
15     중구       400
25    용산구       319
32    성동구       419
40    광진구       396
49   동대문구       404
57    중랑구       535
64    성북구       511
73    강북구       394
82    도봉구       446
92    노원구      1383
102   은평구       846
112  서대문구       253
121   마포구       393
131   양천구       728
139   강서구      1073
148   구로구       811
158   금천구       282
167  영등포구       420
176   동작구       377
184   관악구       549
194   서초구       279
204   강남구       486
215   송파구       927
225   강동구       635

In [114]:
#2021-일반고 대학진학률
df_univ_no11 = df13.query('학제 in ["(일반고)"]')
df_univ_no11['졸업자'] = df_univ_no11['졸업자'].astype('float')
df_univ_no11['국내대학진학자'] = df_univ_no11['국내대학진학자'].astype('float')
df_univ_no11['일반고학생_국내4년제대학진학률'] = (df_univ_no11['국내대학진학자']/df_univ_no11['졸업자'])
df_univ_no12 = df_univ_no11[['행정구역', '일반고학생_국내4년제대학진학률']]
df_univ_no12.sort_values('일반고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2920509547.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no11['졸업자'] = df_univ_no11['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2920509547.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no11['국내대학진학자'] = df_univ_no11['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2920509547.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no11['일반고학생_국내4년제대학진학률'] = (df_univ_no11['국내대학진학자']/df_univ_no11['졸업자'])

     행정구역  일반고학생_국내4년제대학진학률
16     중구          0.529981
113  서대문구          0.522241
93    노원구          0.506126
50   동대문구          0.503759
185   관악구          0.492428
159   금천구          0.489496
177   동작구          0.489101
5     종로구          0.487805
205   강남구          0.484888
26    용산구          0.481667
65    성북구          0.479695
226   강동구          0.479332
103   은평구          0.478292
140   강서구          0.471524
122   마포구          0.469659
216   송파구          0.463590
83    도봉구          0.461282
58    중랑구          0.460224
132   양천구          0.443933
195   서초구          0.443216
41    광진구          0.434906
149   구로구          0.430439
168  영등포구          0.425141
33    성동구          0.423849
74    강북구          0.421927

In [118]:
#2021-특목고대학진학률
df_univ_sp11 = df13.query('학제 in ["(특목고)"]')
df_univ_sp11['졸업자'] = df_univ_sp11['졸업자'].astype('float')
df_univ_sp11['국내대학진학자'] = df_univ_sp11['국내대학진학자'].astype('float')
df_univ_sp11['특목고학생_국내4년제대학진학률'] = (df_univ_sp11['국내대학진학자']/df_univ_sp11['졸업자'])
df_univ_sp12 = df_univ_sp11[['행정구역', '특목고학생_국내4년제대학진학률']]
df_univ_sp12.sort_values('특목고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2520116744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp11['졸업자'] = df_univ_sp11['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2520116744.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp11['국내대학진학자'] = df_univ_sp11['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2520116744.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp11['특목고학생_국내4년제대학진학률'] = (df_univ_sp11['국내대학진학자']/df_univ_sp11['졸업자'])

     행정구역  특목고학생_국내4년제대학진학률
160   금천구          0.831395
114  서대문구          0.784722
217   송파구          0.747967
42    광진구          0.684641
227   강동구          0.653153
6     종로구          0.648953
17     중구          0.644444
141   강서구          0.586758
150   구로구          0.584270
84    도봉구          0.568182
66    성북구          0.505181
206   강남구          0.270161
186   관악구          0.000000

In [121]:
#2021-특성화고 대학진학률
df_univ_sd11 = df13.query('학제 in ["(특성화고)"]')
df_univ_sd11['졸업자'] = df_univ_sd11['졸업자'].astype('float')
df_univ_sd11['국내대학진학자'] = df_univ_sd11['국내대학진학자'].astype('float')
df_univ_sd11['특성화고학생_국내4년제대학진학률'] = (df_univ_sd11['국내대학진학자']/df_univ_sd11['졸업자'])
df_univ_sd12 = df_univ_sd11[['행정구역', '특성화고학생_국내4년제대학진학률']]
df_univ_sd12.sort_values('특성화고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1856830119.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd11['졸업자'] = df_univ_sd11['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1856830119.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd11['국내대학진학자'] = df_univ_sd11['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1856830119.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd11['특성화고학생_국내4년제대학진학률'] = (df_univ_sd11['국내대학진학자']/df_univ_sd11['졸업자'])

     행정구역  특성화고학생_국내4년제대학진학률
7     종로구           0.251208
207   강남구           0.248120
27    용산구           0.236045
133   양천구           0.219949
59    중랑구           0.193370
228   강동구           0.191781
104   은평구           0.176577
34    성동구           0.175847
123   마포구           0.163522
94    노원구           0.145047
169  영등포구           0.141414
75    강북구           0.133333
51   동대문구           0.130653
151   구로구           0.129032
187   관악구           0.119011
18     중구           0.115226
218   송파구           0.109504
142   강서구           0.096903
161   금천구           0.090566
85    도봉구           0.084906
67    성북구           0.077170
178   동작구           0.057940
196   서초구           0.057471

In [123]:
#2021-자율고 대학진학률
df_univ_ah11 = df13.query('학제 in ["(자율고)"]')
df_univ_ah11['졸업자'] = df_univ_ah11['졸업자'].astype('float')
df_univ_ah11['국내대학진학자'] = df_univ_ah11['국내대학진학자'].astype('float')
df_univ_ah11['자율고학생_국내4년제대학진학률'] = (df_univ_ah11['국내대학진학자']/df_univ_ah11['졸업자'])
df_univ_ah12 = df_univ_ah11[['행정구역', '자율고학생_국내4년제대학진학률']]
df_univ_ah12.sort_values('자율고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3262790791.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah11['졸업자'] = df_univ_ah11['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3262790791.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah11['국내대학진학자'] = df_univ_ah11['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3262790791.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah11['자율고학생_국내4년제대학진학률'] = (df_univ_ah11['국내대학진학자']/df_univ_ah11['졸업자'])

     행정구역  자율고학생_국내4년제대학진학률
105   은평구          0.692683
86    도봉구          0.664865
229   강동구          0.585586
124   마포구          0.577381
219   송파구          0.574866
52   동대문구          0.556553
170  영등포구          0.549645
35    성동구          0.530769
19     중구          0.525799
197   서초구          0.525032
8     종로구          0.514431
134   양천구          0.511485
76    강북구          0.504587
115  서대문구          0.467742
208   강남구          0.462843

In [98]:
#2020년 행정구역별 고등학생의 4년제 대학진학률
import pandas as pd

df21 = pd.read_csv('행정구역별2020.csv')
df22 = df21.query('학제 in ["고등학교", "(일반고)", "(특목고)", "(특성화고)", "(자율고)"]')

df23= df22.rename(columns = {df22.columns[5]:"졸업후진학자",
                             df22.columns[6]:"졸업후취업자",
                             df22.columns[7]:"졸업후입대자",
                             df22.columns[8]:"졸업후기타",
                             df22.columns[9]:"국내전문대학진학자",
                             df22.columns[10]:"국내교육대학진학자",
                             df22.columns[11]:"국내대학진학자",
                             df22.columns[12]:"국내각종학교진학자",
                             df22.columns[13]:"국외전문대학진학자",
                             df22.columns[14]:"국외대학진학자"})


df23_univ = df23.query('학제 in ["고등학교"]')
df23_univ['졸업자'] = df23_univ['졸업자'].astype('float')
df23_univ['국내대학진학자'] = df23_univ['국내대학진학자'].astype('float')

df23_univ['국내4년제대학진학률'] = (df23_univ['국내대학진학자']/df23_univ['졸업자'])

df23_univ


#고등학교=일반고+특목고+특성화고+자율고

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3303903214.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df23_univ['졸업자'] = df23_univ['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3303903214.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df23_univ['국내대학진학자'] = df23_univ['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3303903214.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df23_univ['국내4년제대학진학률'] = (df23_univ['국내대학진학자']/df23_univ['졸업자'])

,시도,행정구역,학제,입학자,졸업자,졸업후진학자,졸업후취업자,졸업후입대자,졸업후기타,국내전문대학진학자,국내교육대학진학자,국내대학진학자,국내각종학교진학자,국외전문대학진학자,국외대학진학자,국내4년제대학진학률
4,서울,종로구,고등학교,2814,3219.0,1870,197,3,1149,440,2,1363.0,49,0,16,0.423423
15,서울,중구,고등학교,2176,2380.0,1120,464,75,721,405,4,709.0,0,0,2,0.297899
25,서울,용산구,고등학교,1801,2155.0,1141,245,4,765,378,3,740.0,4,0,16,0.343387
33,서울,성동구,고등학교,1421,1979.0,1170,152,2,655,500,6,662.0,0,1,1,0.334512
41,서울,광진구,고등학교,2463,2697.0,1690,26,3,978,418,8,1248.0,3,0,13,0.462736
51,서울,동대문구,고등학교,2294,2628.0,1768,186,9,665,539,3,1210.0,15,0,1,0.460426
59,서울,중랑구,고등학교,1999,2298.0,1440,214,12,632,574,4,859.0,0,0,3,0.373803
67,서울,성북구,고등학교,2731,3064.0,1911,351,1,801,644,7,1253.0,2,0,5,0.408943
77,서울,강북구,고등학교,1783,1926.0,1181,83,2,660,489,4,682.0,0,0,6,0.354102
86,서울,도봉구,고등학교,2226,2520.0,1479,127,0,914,520,9,936.0,0,0,14,0.371429
96,서울,노원구,고등학교,6659,7567.0,4482,611,61,2413,1593,21,2860.0,3,0,5,0.377957
107,서울,은평구,고등학교,4198,4525.0,2654,509,15,1347,897,15,1725.0,2,0,15,0.381215
117,서울,서대문구,고등학교,1672,1969.0,1292,74,1,602,352,8,922.0,8,0,2,0.468258
126,서울,마포구,고등학교,2030,2139.0,1223,162,1,753,459,4,756.0,1,0,3,0.353436
136,서울,양천구,고등학교,4083,4614.0,2748,93,4,1769,861,18,1860.0,0,0,9,0.403121
144,서울,강서구,고등학교,4951,5725.0,3391,462,4,1868,1181,16,2168.0,7,0,19,0.378690
154,서울,구로구,고등학교,3086,3398.0,2204,204,9,981,1074,9,1117.0,2,0,2,0.328723
165,서울,금천구,고등학교,1340,1485.0,989,184,0,312,370,4,584.0,28,0,3,0.393266
175,서울,영등포구,고등학교,1924,2169.0,1351,78,0,740,497,6,839.0,2,0,7,0.386814
184,서울,동작구,고등학교,1981,2145.0,1184,198,2,761,436,2,742.0,0,0,4,0.345921
192,서울,관악구,고등학교,3030,3364.0,1964,396,0,1004,713,3,1243.0,1,0,4,0.369501
203,서울,서초구,고등학교,3326,3716.0,1794,57,1,1864,337,15,1425.0,5,0,12,0.383477
213,서울,강남구,고등학교,6036,6578.0,3331,324,39,2884,505,18,2762.0,2,4,40,0.419884
224,서울,송파구,고등학교,4874,5472.0,3158,325,61,1928,915,18,2196.0,4,0,25,0.401316
234,서울,강동구,고등학교,3618,3906.0,2552,133,2,1219,822,9,1703.0,5,0,13,0.435996

In [99]:
df23_univ1 = df23_univ[['행정구역', '국내4년제대학진학률']]
df23_univ1.sort_values('국내4년제대학진학률', ascending = False)

     행정구역  국내4년제대학진학률
117  서대문구    0.468258
41    광진구    0.462736
51   동대문구    0.460426
234   강동구    0.435996
4     종로구    0.423423
213   강남구    0.419884
67    성북구    0.408943
136   양천구    0.403121
224   송파구    0.401316
165   금천구    0.393266
175  영등포구    0.386814
203   서초구    0.383477
107   은평구    0.381215
144   강서구    0.378690
96    노원구    0.377957
59    중랑구    0.373803
86    도봉구    0.371429
192   관악구    0.369501
77    강북구    0.354102
126   마포구    0.353436
184   동작구    0.345921
25    용산구    0.343387
33    성동구    0.334512
154   구로구    0.328723
15     중구    0.297899

In [124]:
#2020-일반고 대학진학률
df_univ_no21 = df23.query('학제 in ["(일반고)"]')
df_univ_no21['졸업자'] = df_univ_no21['졸업자'].astype('float')
df_univ_no21['국내대학진학자'] = df_univ_no21['국내대학진학자'].astype('float')
df_univ_no21['일반고학생_국내4년제대학진학률'] = (df_univ_no21['국내대학진학자']/df_univ_no21['졸업자'])
df_univ_no22 = df_univ_no21[['행정구역', '일반고학생_국내4년제대학진학률']]
df_univ_no22.sort_values('일반고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\524289134.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no21['졸업자'] = df_univ_no21['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\524289134.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no21['국내대학진학자'] = df_univ_no21['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\524289134.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no21['일반고학생_국내4년제대학진학률'] = (df_univ_no21['국내대학진학자']/df_univ_no21['졸업자'])

     행정구역  일반고학생_국내4년제대학진학률
16     중구          0.548387
52   동대문구          0.495114
193   관악구          0.470872
97    노원구          0.466454
166   금천구          0.464771
235   강동구          0.457174
108   은평구          0.457033
214   강남구          0.448398
145   강서구          0.439075
68    성북구          0.435535
185   동작구          0.423331
5     종로구          0.422192
127   마포구          0.421053
26    용산구          0.419157
225   송파구          0.419084
118  서대문구          0.413408
137   양천구          0.406619
60    중랑구          0.404152
204   서초구          0.399711
42    광진구          0.399573
176  영등포구          0.394644
34    성동구          0.380769
87    도봉구          0.373333
155   구로구          0.373054
78    강북구          0.358804

In [125]:
#2020-특목고 대학진학률
df_univ_sp21 = df23.query('학제 in ["(특목고)"]')
df_univ_sp21['졸업자'] = df_univ_sp21['졸업자'].astype('float')
df_univ_sp21['국내대학진학자'] = df_univ_sp21['국내대학진학자'].astype('float')
df_univ_sp21['특목고학생_국내4년제대학진학률'] = (df_univ_sp21['국내대학진학자']/df_univ_sp21['졸업자'])
df_univ_sp22 = df_univ_sp21[['행정구역', '특목고학생_국내4년제대학진학률']]
df_univ_sp22.sort_values('특목고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3617561915.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp21['졸업자'] = df_univ_sp21['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3617561915.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp21['국내대학진학자'] = df_univ_sp21['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3617561915.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp21['특목고학생_국내4년제대학진학률'] = (df_univ_sp21['국내대학진학자']/df_univ_sp21['졸업자'])

     행정구역  특목고학생_국내4년제대학진학률
119  서대문구          0.833333
226   송파구          0.757353
236   강동구          0.685185
43    광진구          0.671949
17     중구          0.656250
167   금천구          0.650888
146   강서구          0.639013
6     종로구          0.561208
88    도봉구          0.531100
69    성북구          0.505236
156   구로구          0.504808
215   강남구          0.236140
194   관악구          0.037037

In [126]:
#2020-특성화고 대학진학률
df_univ_sd21 = df23.query('학제 in ["(특성화고)"]')
df_univ_sd21['졸업자'] = df_univ_sd21['졸업자'].astype('float')
df_univ_sd21['국내대학진학자'] = df_univ_sd21['국내대학진학자'].astype('float')
df_univ_sd21['특성화고학생_국내4년제대학진학률'] = (df_univ_sd21['국내대학진학자']/df_univ_sd21['졸업자'])
df_univ_sd22 = df_univ_sd21[['행정구역', '특성화고학생_국내4년제대학진학률']]
df_univ_sd22.sort_values('특성화고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4262064374.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd21['졸업자'] = df_univ_sd21['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4262064374.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd21['국내대학진학자'] = df_univ_sd21['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\4262064374.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd21['특성화고학생_국내4년제대학진학률'] = (df_univ_sd21['국내대학진학자']/df_univ_sd21['졸업자'])

     행정구역  특성화고학생_국내4년제대학진학률
216   강남구           0.224026
61    중랑구           0.200000
27    용산구           0.183261
35    성동구           0.167428
177  영등포구           0.166667
138   양천구           0.163399
7     종로구           0.152220
98    노원구           0.139247
128   마포구           0.137097
109   은평구           0.130148
237   강동구           0.117886
195   관악구           0.102921
18     중구           0.098814
157   구로구           0.091907
147   강서구           0.086133
186   동작구           0.078838
53   동대문구           0.075614
79    강북구           0.071823
89    도봉구           0.057644
227   송파구           0.055655
168   금천구           0.040486
205   서초구           0.030303
70    성북구           0.016502

In [132]:
#2020-자율고 대학진학률
df_univ_ah21 = df23.query('학제 in ["(자율고)"]')
df_univ_ah21['졸업자'] = df_univ_ah21['졸업자'].astype('float')
df_univ_ah21['국내대학진학자'] = df_univ_ah21['국내대학진학자'].astype('float')
df_univ_ah21['자율고학생_국내4년제대학진학률'] = (df_univ_ah21['국내대학진학자']/df_univ_ah21['졸업자'])
df_univ_ah22 = df_univ_ah21[['행정구역', '자율고학생_국내4년제대학진학률']]
df_univ_ah22.sort_values('자율고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3950600042.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah21['졸업자'] = df_univ_ah21['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3950600042.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah21['국내대학진학자'] = df_univ_ah21['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3950600042.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah21['자율고학생_국내4년제대학진학률'] = (df_univ_ah21['국내대학진학자']/df_univ_ah21['졸업자'])

     행정구역  자율고학생_국내4년제대학진학률
110   은평구          0.720588
54   동대문구          0.645235
90    도봉구          0.587379
228   송파구          0.580381
139   양천구          0.547059
120  서대문구          0.538847
238   강동구          0.538283
71    성북구          0.538043
8     종로구          0.491393
19     중구          0.477740
36    성동구          0.470480
178  영등포구          0.445652
80    강북구          0.438078
217   강남구          0.436407
99    노원구          0.425439
28    용산구          0.420382
129   마포구          0.416761
62    중랑구          0.411765
206   서초구          0.400513
44    광진구          0.391753
158   구로구          0.372213
196   관악구          0.354331
169   금천구          0.338462
148   강서구          0.328947

In [101]:
#2019년 행정구역별 고등학생의 4년제 대학진학률
import pandas as pd

df31 = pd.read_csv('행정구역별2019.csv')
df32 = df31.query('학제 in ["고등학교", "(일반고)", "(특목고)", "(특성화고)", "(자율고)"]')

df33= df32.rename(columns = {df32.columns[5]:"졸업후진학자",
                             df32.columns[6]:"졸업후취업자",
                             df32.columns[7]:"졸업후입대자",
                             df32.columns[8]:"졸업후기타",
                             df32.columns[9]:"국내전문대학진학자",
                             df32.columns[10]:"국내교육대학진학자",
                             df32.columns[11]:"국내대학진학자",
                             df32.columns[12]:"국내각종학교진학자",
                             df32.columns[13]:"국외전문대학진학자",
                             df32.columns[14]:"국외대학진학자"})


df33_univ = df33.query('학제 in ["고등학교"]')
df33_univ['졸업자'] = df33_univ['졸업자'].astype('float')
df33_univ['국내대학진학자'] = df33_univ['국내대학진학자'].astype('float')

df33_univ['국내4년제대학진학률'] = (df33_univ['국내대학진학자']/df33_univ['졸업자'])


df33_univ

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2092521647.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df33_univ['졸업자'] = df33_univ['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2092521647.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df33_univ['국내대학진학자'] = df33_univ['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\2092521647.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df33_univ['국내4년제대학진학률'] = (df33_univ['국내대학진학자']/df33_univ['졸업자'])

,시도,행정구역,학제,입학자,졸업자,졸업후진학자,졸업후취업자,졸업후입대자,졸업후기타,국내전문대학진학자,국내교육대학진학자,국내대학진학자,국내각종학교진학자,국외전문대학진학자,국외대학진학자,국내4년제대학진학률
4,서울,종로구,고등학교,2894,3737.0,2043,226,0,1468,525,4,1434.0,28,1,51,0.383730
15,서울,중구,고등학교,2367,2669.0,1167,595,0,907,429,2,708.0,23,0,5,0.265268
25,서울,용산구,고등학교,1965,2444.0,1366,260,0,818,505,3,840.0,3,0,15,0.343699
33,서울,성동구,고등학교,1504,2059.0,1048,201,0,810,455,4,586.0,0,0,3,0.284604
41,서울,광진구,고등학교,2551,3343.0,2043,35,0,1265,560,6,1450.0,0,0,27,0.433742
51,서울,동대문구,고등학교,2368,3114.0,1781,352,40,941,639,3,1130.0,1,0,8,0.362877
59,서울,중랑구,고등학교,2151,2769.0,1699,247,15,808,722,1,966.0,4,1,5,0.348862
67,서울,성북구,고등학교,2962,3553.0,2049,290,3,1211,662,9,1351.0,4,0,23,0.380242
77,서울,강북구,고등학교,1875,2200.0,1265,103,1,831,515,4,721.0,0,1,24,0.327727
86,서울,도봉구,고등학교,2260,2725.0,1513,140,2,1070,481,6,1006.0,1,0,19,0.369174
96,서울,노원구,고등학교,7015,8976.0,5085,679,13,3199,1843,20,3200.0,7,1,14,0.356506
107,서울,은평구,고등학교,4485,5193.0,2974,740,2,1477,1097,12,1815.0,13,0,37,0.349509
117,서울,서대문구,고등학교,1742,2142.0,1282,67,0,793,379,7,892.0,2,0,2,0.416433
126,서울,마포구,고등학교,2107,2392.0,1278,174,0,940,499,6,767.0,0,0,6,0.320652
136,서울,양천구,고등학교,4246,5444.0,2939,181,3,2321,856,21,2046.0,5,0,11,0.375827
144,서울,강서구,고등학교,5180,6264.0,3418,590,6,2250,1261,18,2086.0,15,11,27,0.333014
154,서울,구로구,고등학교,3196,3844.0,2352,244,0,1248,1106,6,1217.0,10,0,13,0.316597
165,서울,금천구,고등학교,1389,1726.0,1041,222,0,463,373,0,665.0,3,0,0,0.385284
175,서울,영등포구,고등학교,2044,2539.0,1546,90,0,903,628,3,910.0,0,0,5,0.358409
184,서울,동작구,고등학교,2044,2487.0,1282,310,0,895,534,2,741.0,0,0,5,0.297949
193,서울,관악구,고등학교,3206,3749.0,2128,501,0,1120,857,15,1239.0,0,1,16,0.330488
204,서울,서초구,고등학교,3334,4262.0,2217,73,6,1966,362,9,1830.0,0,0,16,0.429376
214,서울,강남구,고등학교,6063,7916.0,3549,384,0,3983,571,9,2937.0,3,0,29,0.371021
225,서울,송파구,고등학교,5014,6672.0,3743,391,10,2528,1138,10,2577.0,0,0,18,0.386241
235,서울,강동구,고등학교,3725,4587.0,2762,137,0,1688,907,14,1821.0,1,0,19,0.396991

In [102]:
df33_univ1 = df33_univ[['행정구역', '국내4년제대학진학률']]
df33_univ1.sort_values('국내4년제대학진학률', ascending = False)

     행정구역  국내4년제대학진학률
41    광진구    0.433742
204   서초구    0.429376
117  서대문구    0.416433
235   강동구    0.396991
225   송파구    0.386241
165   금천구    0.385284
4     종로구    0.383730
67    성북구    0.380242
136   양천구    0.375827
214   강남구    0.371021
86    도봉구    0.369174
51   동대문구    0.362877
175  영등포구    0.358409
96    노원구    0.356506
107   은평구    0.349509
59    중랑구    0.348862
25    용산구    0.343699
144   강서구    0.333014
193   관악구    0.330488
77    강북구    0.327727
126   마포구    0.320652
154   구로구    0.316597
184   동작구    0.297949
33    성동구    0.284604
15     중구    0.265268

In [128]:
#2019-일반고 대학진학률
df_univ_no31 = df33.query('학제 in ["(일반고)"]')
df_univ_no31['졸업자'] = df_univ_no31['졸업자'].astype('float')
df_univ_no31['국내대학진학자'] = df_univ_no31['국내대학진학자'].astype('float')
df_univ_no31['일반고학생_국내4년제대학진학률'] = (df_univ_no31['국내대학진학자']/df_univ_no31['졸업자'])
df_univ_no32 = df_univ_no31[['행정구역', '일반고학생_국내4년제대학진학률']]
df_univ_no32.sort_values('일반고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3507819132.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no31['졸업자'] = df_univ_no31['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3507819132.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no31['국내대학진학자'] = df_univ_no31['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\3507819132.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_no31['일반고학생_국내4년제대학진학률'] = (df_univ_no31['국내대학진학자']/df_univ_no31['졸업자'])

     행정구역  일반고학생_국내4년제대학진학률
166   금천구          0.472843
52   동대문구          0.436535
97    노원구          0.431972
205   서초구          0.428787
194   관악구          0.418004
108   은평구          0.409770
226   송파구          0.405794
137   양천구          0.402932
236   강동구          0.401644
26    용산구          0.401148
16     중구          0.398907
127   마포구          0.394261
68    성북구          0.393202
215   강남구          0.389848
42    광진구          0.389161
5     종로구          0.387185
60    중랑구          0.382086
118  서대문구          0.373134
145   강서구          0.368834
176  영등포구          0.362128
185   동작구          0.349736
34    성동구          0.349398
87    도봉구          0.348282
155   구로구          0.348228
78    강북구          0.330084

In [129]:
#2019-특목고 대학진학률
df_univ_sp31 = df33.query('학제 in ["(특목고)"]')
df_univ_sp31['졸업자'] = df_univ_sp31['졸업자'].astype('float')
df_univ_sp31['국내대학진학자'] = df_univ_sp31['국내대학진학자'].astype('float')
df_univ_sp31['특목고학생_국내4년제대학진학률'] = (df_univ_sp31['국내대학진학자']/df_univ_sp31['졸업자'])
df_univ_sp32 = df_univ_sp31[['행정구역', '특목고학생_국내4년제대학진학률']]
df_univ_sp32.sort_values('특목고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1034342584.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp31['졸업자'] = df_univ_sp31['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1034342584.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp31['국내대학진학자'] = df_univ_sp31['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1034342584.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sp31['특목고학생_국내4년제대학진학률'] = (df_univ_sp31['국내대학진학자']/df_univ_sp31['졸업자'])

     행정구역  특목고학생_국내4년제대학진학률
119  서대문구          0.784173
227   송파구          0.708661
167   금천구          0.689266
237   강동구          0.679167
43    광진구          0.670846
146   강서구          0.651316
17     중구          0.592105
6     종로구          0.570747
88    도봉구          0.568889
156   구로구          0.495122
69    성북구          0.469657
216   강남구          0.233954
195   관악구          0.000000

In [130]:
#2019-특성화고 대학진학률
df_univ_sd31 = df33.query('학제 in ["(특성화고)"]')
df_univ_sd31['졸업자'] = df_univ_sd31['졸업자'].astype('float')
df_univ_sd31['국내대학진학자'] = df_univ_sd31['국내대학진학자'].astype('float')
df_univ_sd31['특성화고학생_국내4년제대학진학률'] = (df_univ_sd31['국내대학진학자']/df_univ_sd31['졸업자'])
df_univ_sd32 = df_univ_sd31[['행정구역', '특성화고학생_국내4년제대학진학률']]
df_univ_sd32.sort_values('특성화고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\519232930.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd31['졸업자'] = df_univ_sd31['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\519232930.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd31['국내대학진학자'] = df_univ_sd31['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\519232930.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_sd31['특성화고학생_국내4년제대학진학률'] = (df_univ_sd31['국내대학진학자']/df_univ_sd31['졸업자'])

     행정구역  특성화고학생_국내4년제대학진학률
27    용산구           0.205421
61    중랑구           0.184987
79    강북구           0.171875
217   강남구           0.160883
35    성동구           0.142857
138   양천구           0.129944
98    노원구           0.116514
238   강동구           0.103586
128   마포구           0.102119
7     종로구           0.099130
109   은평구           0.098387
157   구로구           0.097411
53   동대문구           0.093502
147   강서구           0.091211
18     중구           0.087127
177  영등포구           0.081633
186   동작구           0.078351
196   관악구           0.074667
89    도봉구           0.052632
228   송파구           0.044092
206   서초구           0.037037
70    성북구           0.031579
168   금천구           0.013746

In [131]:
#2019-자율고 대학진학률
df_univ_ah31 = df33.query('학제 in ["(자율고)"]')
df_univ_ah31['졸업자'] = df_univ_ah31['졸업자'].astype('float')
df_univ_ah31['국내대학진학자'] = df_univ_ah31['국내대학진학자'].astype('float')
df_univ_ah31['자율고학생_국내4년제대학진학률'] = (df_univ_ah31['국내대학진학자']/df_univ_ah31['졸업자'])
df_univ_ah32 = df_univ_ah31[['행정구역', '자율고학생_국내4년제대학진학률']]
df_univ_ah32.sort_values('자율고학생_국내4년제대학진학률', ascending = False)

C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1481170770.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah31['졸업자'] = df_univ_ah31['졸업자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1481170770.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah31['국내대학진학자'] = df_univ_ah31['국내대학진학자'].astype('float')
C:\Users\onlyo\AppData\Local\Temp\ipykernel_14532\1481170770.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_univ_ah31['자율고학생_국내4년제대학진학률'] = (df_univ_ah31['국내대학진학자']/df_univ_ah31['졸업자'])

     행정구역  자율고학생_국내4년제대학진학률
110   은평구          0.763285
71    성북구          0.697561
90    도봉구          0.674479
239   강동구          0.542141
207   서초구          0.513479
229   송파구          0.491686
120  서대문구          0.463291
8     종로구          0.439887
178  영등포구          0.438655
54   동대문구          0.423541
19     중구          0.414986
139   양천구          0.399123
218   강남구          0.388973
36    성동구          0.387658
28    용산구          0.382857
158   구로구          0.380178
80    강북구          0.374126
129   마포구          0.368026
187   동작구          0.359322
62    중랑구          0.352848
197   관악구          0.348485
99    노원구          0.347328
148   강서구          0.299242
169   금천구          0.297806
44    광진구          0.266932